/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Code: typeof import('./src/components/code.vue')['default']
    ComputeCode: typeof import('./src/components/computeCode.vue')['default']
    FileUpload: typeof import('./src/components/common/fileUpload.vue')['default']
    Pagination: typeof import('./src/components/common/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
